// packages/react/src/google-translate-select.tsx
import React, { useEffect, useMemo, useState } from 'react'
import cs from 'classnames'
import {
  GOOGLE_TRANSLATE_COOKIE_NAME,
  GOOGLE_TRANSLATE_JSSDK_URL,
  GOOGLE_TRANSLATE_ORIGINAL_DOM_ID,
  GOOGLE_TRANSLATE_ORIGINAL_SELECT_CLASSNAME,
  GOOGLE_TRANSLATE_SELECT_LANGUAGES,
  GOOGLE_TRANSLATE_STOP_TRANSLATE_CLASSNAME,
} from '@google-translate-select/constants'
import {
  GoogleTranslateFireEvent,
  createGoogleTranslateJsonpCallback,
  createNamespace,
  createScriptTag,
  createStyleTag,
  getCookie,
  isString,
  useMutationObserver,
} from '@google-translate-select/utils'
import '@google-translate-select/theme-chalk/src/index.scss'
import type { UseMutationObserverReturn } from '@google-translate-select/utils'
import type { IGoogleTranslateProps } from './types/props'

const ns = createNamespace('select')

export default function GoogleTranslateSelect(props: IGoogleTranslateProps) {
  const {
    languages = GOOGLE_TRANSLATE_SELECT_LANGUAGES,
    defaultLanguageCode = 'en',
    defaultPageLanguageCode = 'en',
    fetchBrowserLanguage = true,
    animateTimeout = 150,
    dropdownClassName = '',
    dropdownStyles = {},
    showArrow = true,
    trigger = 'hover',
    className = '',
    select,
  } = props

  const [visible, setVisible] = useState<boolean>(false)
  const [selectedLanguageCode, changeSelectedLanguageCode] =
    useState<string>('')
  const [jsonCallbackFnName, setJsonCallbackFnName] = useState<string>('')
  const [
    googleTranslateOriginSelectObserve,
    setGoogleTranslateOriginSelectObserve,
  ] = useState<Partial<UseMutationObserverReturn> | null>({})
  const [htmlAttrLangObserve, setHtmlAttrLangObserve] =
    useState<Partial<UseMutationObserverReturn> | null>({})
  const [flag, setFlag] = useState<boolean>(true)
  const [timeoutId, setTimeoutId] = useState<number>(-1)

  /**
   * get current select language
   */
  const getSelectedLanguageOption = (code: string) => {
    const selectedLanguageObject = languages.find(
      (language) => language.code === code
    )
    const defaultSelectedLanguageObject = languages.find(
      (language) => language.code === defaultLanguageCode
    )

    return selectedLanguageObject
      ? selectedLanguageObject
      : defaultSelectedLanguageObject
  }

  const selectedLanguageOption = useMemo(
    () => getSelectedLanguageOption(selectedLanguageCode),
    [selectedLanguageCode]
  )

  useEffect(() => {
    createGoogleTranslate()
    createHtmlAttrLangObserve()
  }, [])

  useEffect(() => {
    createScript()
  }, [jsonCallbackFnName])

  useEffect(() => {
    if (htmlAttrLangObserve?.start) {
      htmlAttrLangObserve.start()
    }
    return () => {
      if (htmlAttrLangObserve?.stop) {
        htmlAttrLangObserve.stop()
      }
    }
  }, [htmlAttrLangObserve])

  useEffect(() => {
    if (googleTranslateOriginSelectObserve?.start) {
      googleTranslateOriginSelectObserve.start()
    }
    return () => {
      if (googleTranslateOriginSelectObserve?.stop) {
        googleTranslateOriginSelectObserve.stop()
      }
    }
  }, [googleTranslateOriginSelectObserve])

  useEffect(() => {
    if (googleTranslateOriginSelectObserve?.stop) {
      googleTranslateOriginSelectObserve!.stop!()
    }
  }, [flag])

  /**
   * When GoogleTranslate's original executes, the attribute 'lang' of HTML will have an auto state,
   * in order to overwrite the auto state, we call the 'handleTranslate' again
   */
  const createHtmlAttrLangObserve = () => {
    const observer = useMutationObserver(
      document.querySelector('html')!,
      (records) => {
        records.forEach((record) => {
          if (record.attributeName === 'lang') {
            const currentValue = (record.target as HTMLElement).getAttribute(
              'lang'
            )
            const oldValue = record.oldValue
            // 修复auto的中间状态，如果页面当中内容较多，gt会有一个翻译的过程，就会抛出lang = auto，此时我们手动再触发一次翻译覆盖掉上次未进行完的翻译操作
            if (
              oldValue !== currentValue &&
              oldValue &&
              oldValue !== 'auto' &&
              currentValue === 'auto'
            ) {
              handleTranslate(selectedLanguageCode)
            }
          }
        })
      },
      {
        attributes: true,
        attributeOldValue: true,
      }
    )
    setHtmlAttrLangObserve(observer)
  }

  /**
   * GoogleTranslate init
   */
  const createGoogleTranslate = () => {
    createStyle()
    createJsonCallback()
  }

  /**
   * pass jsonp callback to GoogleTranslate
   */
  const createScript = () => {
    if (!jsonCallbackFnName) {
      return null
    }

    return createScriptTag(
      `${GOOGLE_TRANSLATE_JSSDK_URL}?cb=${jsonCallbackFnName}`
    )
  }

  /**
   * create jsonp callback for GoogleTranslate, when GoogleTranslate loaded callback will be triggered
   */
  const createJsonCallback = () => {
    const { jsonpCallbackName } = createGoogleTranslateJsonpCallback(
      {
        pageLanguage: defaultPageLanguageCode,
      },
      setSelectedLanguageCode
    )
    setJsonCallbackFnName(jsonpCallbackName)
  }

  /**
   * Use browser language、cookie 'googtrans' to get language code
   */
  const setSelectedLanguageCode = () => {
    const googleCookieLanguage = getGoogleCookieLanguage()
    const browserLanguage = fetchBrowserLanguage
      ? isLanguageCodeInLanguages(getBrowserLanguage())
      : ''
    const isGoogleCookieLanguageExist = !!googleCookieLanguage
    const isFetchBrowserLanguageOpen = fetchBrowserLanguage
    const defaultSelectedCode = defaultLanguageCode || 'en'

    const handleLanguageInLanguages = (code: string) => {
      const isLanguageInLanguages = !!languages.find(
        (language) => language.code === code
      )
      return isLanguageInLanguages ? code : defaultSelectedCode
    }
    let selectedCode = defaultSelectedCode
    if (!isGoogleCookieLanguageExist && isFetchBrowserLanguageOpen) {
      selectedCode = handleLanguageInLanguages(browserLanguage)
    } else {
      selectedCode = handleLanguageInLanguages(googleCookieLanguage)
    }

    handleTranslate(selectedCode)
  }

  /**
   * Get browser language
   */
  function getBrowserLanguage() {
    const browserLanguage =
      window.navigator.language || document.documentElement.lang || 'en'

    const filterLanguages = ['zh-CN', 'zh-TW']
    if (filterLanguages.every((l) => l !== browserLanguage)) {
      if (browserLanguage.indexOf('-') > -1) {
        return browserLanguage.split('-')[0]
      }
    }
    return browserLanguage
  }

  /**
   * Determines whether the current select language exists in the props.languages
   *
   * @param code
   */
  function isLanguageCodeInLanguages(code: string) {
    // 如果 code 不存在于语言列表中默认使用英语
    const result = languages.find((language) => language.code === code)
    return result ? code : 'en'
  }

  /**
   * After triggering GoogleTranslate Translate, a cookie called 'googtrans' is generated, such as '/en/tr'
   */
  const getGoogleCookieLanguage = () => {
    const googleTranslateCookie = getCookie(GOOGLE_TRANSLATE_COOKIE_NAME)
    if (googleTranslateCookie) {
      const googleTranslateCookieResult = googleTranslateCookie.split('/')
      return googleTranslateCookieResult[2]
        ? googleTranslateCookieResult[2]
        : 'en'
    } else {
      return ''
    }
  }

  /**
   * dynamic insert style for GoogleTranslate
   */
  const createStyle = () => {
    return createStyleTag(
      `body { top: 0 !important; } .skiptranslate { display: none !important; }`
    )
  }

  const handleDropdownShow = () => {
    clearTimeout(timeoutId)
    setTimeoutId(
      window.setTimeout(() => {
        setVisible(true)
      }, animateTimeout)
    )
  }

  const handleDropdownHide = () => {
    clearTimeout(timeoutId)
    setTimeoutId(
      window.setTimeout(() => {
        setVisible(false)
      }, animateTimeout)
    )
  }

  /**
   * Triggers translations by observe changes in the DOM of GoogleTranslate's original select.
   *
   * Because the callback function passed in JSONP can only be called after the GOOGLE_TRANSLATE_JSSDK_URL resource is loaded,
   * and the GOOGLE_TRANSLATE_JSSDK_URL will import the resource that generated the original DOM, observe is used here🤓
   */
  const createGoogleTranslateOriginSelectObserve = (code: string) => {
    const observe = useMutationObserver(
      document.querySelector(GOOGLE_TRANSLATE_ORIGINAL_SELECT_CLASSNAME)!,
      (records) => {
        records.forEach((record) => {
          if (
            record.addedNodes[0] &&
            (record.addedNodes[0] as HTMLOptionElement).value
          ) {
            if (code === (record.addedNodes[0] as HTMLOptionElement).value) {
              triggerTranslate(
                (record.addedNodes[0] as HTMLOptionElement).value
              )
            }
          }
        })
      },
      {
        childList: true,
        subtree: true,
      }
    )
    setGoogleTranslateOriginSelectObserve(observe)
  }

  const triggerTranslate = (select: HTMLSelectElement | string) => {
    if (!select) {
      return
    }
    const selectValue = isString(select) ? select : select.value ?? ''
    const googleTranslateOriginalSelectEl = document.querySelector(
      GOOGLE_TRANSLATE_ORIGINAL_SELECT_CLASSNAME
    ) as HTMLSelectElement
    const googleTranslateSelectEl = document.querySelector(`.${ns.b()}`)

    if (
      !googleTranslateSelectEl ||
      googleTranslateSelectEl.innerHTML.length === 0 ||
      googleTranslateOriginalSelectEl.options.length === 0
    ) {
      createGoogleTranslateOriginSelectObserve(selectValue)
    } else {
      googleTranslateOriginalSelectEl.value = selectValue
      GoogleTranslateFireEvent(googleTranslateOriginalSelectEl, 'change')
      setFlag(!flag)
    }
  }

  const handleTranslate = (code: string) => {
    triggerTranslate(code)
    changeSelectedLanguageCode(code)
    select && select(getSelectedLanguageOption(code))
  }

  if (!languages || !languages.length) {
    return null
  }

  return (
    <>
      <div
        className={cs([
          ns.b(),
          GOOGLE_TRANSLATE_STOP_TRANSLATE_CLASSNAME,
          className,
        ])}
      >
        <div className={ns.b('dropdown')}>
          <div
            className={ns.be('dropdown', 'activator')}
            onMouseEnter={handleDropdownShow}
            onMouseLeave={handleDropdownHide}
          >
            <div className={ns.b('language')}>
              <div className={ns.b('flag')}>
                <div className={ns.be('flag', selectedLanguageOption?.code)} />
              </div>
              {selectedLanguageOption?.name}
            </div>
            {showArrow && (
              <div
                className={cs([ns.b('icon'), visible ? ns.is('reverse') : ''])}
              >
                <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1024 1024">
                  <path
                    fill="currentColor"
                    d="M831.872 340.864 512 652.672 192.128 340.864a30.592 30.592 0 0 0-42.752 0 29.12 29.12 0 0 0 0 41.6L489.664 714.24a32 32 0 0 0 44.672 0l340.288-331.712a29.12 29.12 0 0 0 0-41.728 30.592 30.592 0 0 0-42.752 0z"
                  />
                </svg>
              </div>
            )}
          </div>
          <div
            className={cs([ns.be('dropdown', 'menu'), dropdownClassName])}
            style={{ display: visible ? '' : 'none', ...dropdownStyles }}
            onMouseEnter={handleDropdownShow}
            onMouseLeave={handleDropdownHide}
          >
            <ul>
              {languages.map((language) => {
                return (
                  <li
                    key={`language-${language.code}`}
                    className={cs([
                      ns.be('dropdown', 'menu__item'),
                      selectedLanguageCode === language.code ? 'selected' : '',
                    ])}
                    data-language-code={language.code}
                    onClick={() => {
                      handleTranslate(language.code)
                    }}
                  >
                    <div className={ns.b('language')}>
                      <div className={ns.b('flag')}>
                        <div className={ns.be('flag', language.code)}></div>
                      </div>
                      {language.name}
                    </div>
                  </li>
                )
              })}
            </ul>
          </div>
        </div>
      </div>
      <div id={GOOGLE_TRANSLATE_ORIGINAL_DOM_ID} />
    </>
  )
}

// packages/vue3/src/google-translate-select.vue
<template>
  <div
    v-if="hasLanguages"
    ref="googleTranslateSelectEl"
    :class="getClass"
    @mouseenter="handleDropdownShowByHover"
    @mouseleave="handleDropdownHideByHover"
  >
    <div :class="[ns.b('dropdown')]">
      <div :class="[ns.be('dropdown', 'activator')]">
        <div :class="[ns.b('language')]">
          <div :class="[ns.b('flag')]">
            <div :class="[ns.be('flag', selectedLanguageOption.code)]" />
          </div>
          {{ selectedLanguageOption.name }}
        </div>
        <div
          v-if="showArrow"
          :class="[ns.b('icon'), visible ? ns.is('reverse') : '']"
        >
          <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1024 1024">
            <path
              fill="currentColor"
              d="M831.872 340.864 512 652.672 192.128 340.864a30.592 30.592 0 0 0-42.752 0 29.12 29.12 0 0 0 0 41.6L489.664 714.24a32 32 0 0 0 44.672 0l340.288-331.712a29.12 29.12 0 0 0 0-41.728 30.592 30.592 0 0 0-42.752 0z"
            />
          </svg>
        </div>
      </div>
      <transition name="google-translate-select-zoom-in-top">
        <div
          v-show="visible"
          :class="[ns.be('dropdown', 'menu'), dropdownClassName]"
          :style="dropdownStyle"
        >
          <ul>
            <li
              v-for="language in languages"
              :key="`language-${language.code}`"
              :class="[
                ns.be('dropdown', 'menu__item'),
                hoveredLanguageCode === language.code ? 'hover' : '',
                selectedLanguageCode === language.code ? 'selected' : '',
              ]"
              :data-language-code="language.code"
              @click="() => handleTranslate(language.code)"
              @mouseenter.stop="() => (hoveredLanguageCode = language.code)"
              @mouseleave.stop="() => (hoveredLanguageCode = '')"
            >
              <div :class="[ns.b('language')]">
                <div :class="[ns.b('flag')]">
                  <div :class="[ns.be('flag', language.code)]" />
                </div>
                {{ language.name }}
              </div>
            </li>
          </ul>
        </div>
      </transition>
    </div>
  </div>
  <div :id="GOOGLE_TRANSLATE_ORIGINAL_DOM_ID" />
</template>

<script lang="ts">
import {
  computed,
  defineComponent,
  onBeforeUnmount,
  onMounted,
  ref,
  unref,
} from 'vue'
import {
  GoogleTranslateFireEvent,
  createGoogleTranslateJsonpCallback,
  createNamespace,
  createScriptTag,
  createStyleTag,
  getCookie,
  isString,
  useMutationObserver,
} from '@google-translate-select/utils'
import {
  GOOGLE_TRANSLATE_COOKIE_NAME,
  GOOGLE_TRANSLATE_JSSDK_URL,
  GOOGLE_TRANSLATE_ORIGINAL_DOM_ID,
  GOOGLE_TRANSLATE_ORIGINAL_SELECT_CLASSNAME,
  GOOGLE_TRANSLATE_STOP_TRANSLATE_CLASSNAME,
} from '@google-translate-select/constants'
import '@google-translate-select/theme-chalk/src/index.scss'
import { googleTranslateProps } from './types'
import type { UseMutationObserverReturn } from '@google-translate-select/utils'

const ns = createNamespace('select')

export default defineComponent({
  name: ns.n,
  inheritAttrs: false,
  props: googleTranslateProps,
  emits: ['select'],
  setup(props, { emit, attrs }) {
    const googleTranslateSelectEl = ref<HTMLElement | null>(null)
    const visible = ref<boolean>(false)
    const selectedLanguageCode = ref<string>('')
    const hoveredLanguageCode = ref<string>('')
    const setTimeoutId = ref<number>(-1)
    const jsonCallbackFnName = ref<string>('')
    const googleTranslateOriginSelectObserve =
      ref<Partial<UseMutationObserverReturn> | null>({})
    const htmlAttrLangObserve = ref<Partial<UseMutationObserverReturn> | null>(
      {}
    )

    const getClass = computed(() => {
      return [ns.b(), GOOGLE_TRANSLATE_STOP_TRANSLATE_CLASSNAME, attrs.class]
    })

    const hasLanguages = computed(
      () => props.languages && props.languages.length
    )

    /** cache current select language */
    const selectedLanguageOption = computed(() => getSelectedLanguageOption())

    /**
     * get current select language
     */
    function getSelectedLanguageOption() {
      const selectedLanguageOption = props.languages.find(
        (language) => language.code === unref(selectedLanguageCode)
      )
      if (selectedLanguageOption) {
        return selectedLanguageOption
      } else {
        const defaultSelectedLanguageOption = props.languages.find(
          (language) => language.code === props.defaultLanguageCode
        )
        return defaultSelectedLanguageOption!
      }
    }

    /**
     * dynamic insert style for GoogleTranslate
     */
    function createStyle() {
      return createStyleTag(
        `body { top: 0 !important; } .skiptranslate { display: none !important; }`
      )
    }

    /**
     * create jsonp callback for GoogleTranslate, when GoogleTranslate loaded callback will be triggered
     */
    function createJsonCallback() {
      const pageLanguage = props.defaultPageLanguageCode
      const { jsonpCallbackName } = createGoogleTranslateJsonpCallback(
        {
          pageLanguage,
        },
        setSelectedLanguageCode
      )
      jsonCallbackFnName.value = jsonpCallbackName
    }

    /**
     * pass jsonp callback to GoogleTranslate
     */
    function createScript() {
      return createScriptTag(
        `${GOOGLE_TRANSLATE_JSSDK_URL}?cb=${unref(jsonCallbackFnName)}`
      )
    }

    /**
     * GoogleTranslate init
     */
    function createGoogleTranslate() {
      createStyle()
      createJsonCallback()
      createScript()
    }

    /**
     * Triggers translations by observe changes in the DOM of GoogleTranslate's original select.
     *
     * Because the callback function passed in JSONP can only be called after the GOOGLE_TRANSLATE_JSSDK_URL resource is loaded,
     * and the GOOGLE_TRANSLATE_JSSDK_URL will import the resource that generated the original DOM, observe is used here🤓
     */
    function createGoogleTranslateOriginSelectObserve() {
      googleTranslateOriginSelectObserve.value = useMutationObserver(
        document.querySelector(GOOGLE_TRANSLATE_ORIGINAL_SELECT_CLASSNAME)!,
        (records) => {
          records.forEach((record) => {
            if (
              record.addedNodes[0] &&
              (record.addedNodes[0] as HTMLOptionElement).value
            ) {
              if (
                selectedLanguageCode.value ===
                (record.addedNodes[0] as HTMLOptionElement).value
              ) {
                triggerTranslate(
                  (record.addedNodes[0] as HTMLOptionElement).value
                )
              }
            }
          })
        },
        {
          childList: true,
          subtree: true,
        }
      )

      unref(googleTranslateOriginSelectObserve)!.start!()
    }

    /**
     * When GoogleTranslate's original executes, the attribute 'lang' of HTML will have an auto state,
     * in order to overwrite the auto state, we call the 'handleTranslate' again
     */
    function createHtmlAttrLangObserve() {
      htmlAttrLangObserve.value = useMutationObserver(
        document.querySelector('html')!,
        (records) => {
          records.forEach((record) => {
            if (record.attributeName === 'lang') {
              const currentValue = (record.target as HTMLElement).getAttribute(
                'lang'
              )
              const oldValue = record.oldValue
              // 修复auto的中间状态，如果页面当中内容较多，gt会有一个翻译的过程，就会抛出lang = auto，此时我们手动再触发一次翻译覆盖掉上次未进行完的翻译操作
              if (
                oldValue !== currentValue &&
                oldValue &&
                oldValue !== 'auto' &&
                currentValue === 'auto'
              ) {
                handleTranslate(unref(selectedLanguageCode))
              }
            }
          })
        },
        {
          attributes: true,
          attributeOldValue: true,
        }
      )

      unref(htmlAttrLangObserve)!.start!()
    }

    /**
     * Simulates the change event of select to manually trigger GoogleTranslate
     *
     * @param select
     */
    function triggerTranslate(select: HTMLSelectElement | string) {
      if (!select) return

      let selectValue = ''
      if (isString(select)) {
        selectValue = select
      } else {
        selectValue = select.value ?? ''
      }

      const googleTranslateOriginalSelectEl = document.querySelector(
        GOOGLE_TRANSLATE_ORIGINAL_SELECT_CLASSNAME
      ) as HTMLSelectElement
      const googleTranslateSelectEl = document.querySelector(`.${ns.b()}`)

      if (
        !googleTranslateSelectEl ||
        googleTranslateSelectEl.innerHTML.length === 0 ||
        googleTranslateOriginalSelectEl.options.length === 0
      ) {
        createGoogleTranslateOriginSelectObserve()
      } else {
        googleTranslateOriginalSelectEl.value = selectValue
        GoogleTranslateFireEvent(googleTranslateOriginalSelectEl, 'change')
        unref(googleTranslateOriginSelectObserve) &&
          unref(googleTranslateOriginSelectObserve)!.stop!()
      }
    }

    /**
     * Determines whether the current select language exists in the props.languages
     *
     * @param code
     */
    function isLanguageCodeInLanguages(code: string) {
      // 如果 code 不存在于语言列表中默认使用英语
      const result = props.languages.find((language) => language.code === code)
      return result ? code : 'en'
    }

    /**
     * Get browser language
     */
    function getBrowserLanguage() {
      const browserLanguage =
        window.navigator.language || document.documentElement.lang || 'en'

      const filterLanguages = ['zh-CN', 'zh-TW']
      if (filterLanguages.every((l) => l !== browserLanguage)) {
        if (browserLanguage.indexOf('-') > -1) {
          return browserLanguage.split('-')[0]
        }
      }
      return browserLanguage
    }

    /**
     * After triggering GoogleTranslate Translate, a cookie called 'googtrans' is generated, such as '/en/tr'
     */
    function getGoogleCookieLanguage() {
      const googleTranslateCookie = getCookie(GOOGLE_TRANSLATE_COOKIE_NAME)

      if (googleTranslateCookie) {
        const googleTranslateCookieResult = googleTranslateCookie.split('/')
        return googleTranslateCookieResult[2]
          ? googleTranslateCookieResult[2]
          : 'en'
      } else {
        return ''
      }
    }

    /**
     * Use browser language、cookie 'googtrans' to get language code
     */
    function setSelectedLanguageCode() {
      const isFetchBrowserLanguageOpen = props.fetchBrowserLanguage
      const browserLanguage = isFetchBrowserLanguageOpen
        ? isLanguageCodeInLanguages(getBrowserLanguage())
        : ''
      const googleCookieLanguage = getGoogleCookieLanguage()
      const isGoogleCookieLanguageExist = !!googleCookieLanguage

      const handleDefaultLanguage = () => {
        if (props.defaultLanguageCode) {
          return props.defaultLanguageCode
        } else {
          return 'en'
        }
      }

      const handleBrowserLanguageInLanguages = () => {
        const isBrowserLanguageInLanguages = !!props.languages.find(
          (language) => language.code === browserLanguage
        )
        if (isBrowserLanguageInLanguages) {
          return browserLanguage
        } else {
          return handleDefaultLanguage()
        }
      }

      const handleGoogleCookieLanguageInLanguages = () => {
        const isGoogleCookieLanguageInLanguages = !!props.languages.find(
          (language) => language.code === googleCookieLanguage
        )
        if (isGoogleCookieLanguageInLanguages) {
          return googleCookieLanguage
        } else {
          return handleDefaultLanguage()
        }
      }

      let selectedCode = handleDefaultLanguage()
      if (!isGoogleCookieLanguageExist) {
        // 首次
        if (isFetchBrowserLanguageOpen)
          selectedCode = handleBrowserLanguageInLanguages()
      } else {
        // 非首次
        // 越过浏览器语言判断直接去列表中匹配
        selectedCode = handleGoogleCookieLanguageInLanguages()
      }

      handleTranslate(selectedCode)
    }

    function handleTranslate(code: string) {
      triggerTranslate(code)
      selectedLanguageCode.value = code

      emit('select', getSelectedLanguageOption())
    }

    function clearSettimeout() {
      clearTimeout(unref(setTimeoutId))
      setTimeoutId.value = -1
    }

    function handleDropdownShowByHover(e: Event) {
      if (props.trigger === 'hover') {
        clearSettimeout()
        setTimeoutId.value = window.setTimeout(() => {
          const target = e.target as HTMLElement
          if (
            unref(googleTranslateSelectEl) &&
            unref(googleTranslateSelectEl)?.contains(target)
          ) {
            visible.value = true
          }
        }, 0)
      }
    }

    function handleDropdownHideByHover() {
      if (props.trigger === 'hover') {
        clearSettimeout()
        setTimeoutId.value = window.setTimeout(() => {
          visible.value = false
        }, props.animateTimeout)
      }
    }

    function handleDropdownShowOrHideByClick(e: Event) {
      const target = e.target as HTMLElement
      if (
        unref(googleTranslateSelectEl) &&
        unref(googleTranslateSelectEl)?.contains(target)
      ) {
        visible.value = true
      } else {
        visible.value = false
      }
    }

    onMounted(() => {
      createGoogleTranslate()
      createHtmlAttrLangObserve()

      if (props.trigger === 'click')
        document.addEventListener('click', handleDropdownShowOrHideByClick)
    })

    onBeforeUnmount(() => {
      unref(googleTranslateOriginSelectObserve)!.stop!()
      unref(htmlAttrLangObserve)!.stop!()

      if (props.trigger === 'click')
        document.removeEventListener('click', handleDropdownShowOrHideByClick)
    })

    return {
      ns,
      googleTranslateSelectEl,
      visible,
      selectedLanguageCode,
      hoveredLanguageCode,
      getClass,
      hasLanguages,
      selectedLanguageOption,
      handleTranslate,
      handleDropdownShowByHover,
      handleDropdownHideByHover,
      GOOGLE_TRANSLATE_ORIGINAL_DOM_ID,
    }
  },
})
</script>
